/* ═══ INCIDENTS-DATA.JS — Sub-story / Incident Report data ═══ */

const INCIDENTS = [
  // ── 2020s EVENTS ──
  {
    id:'INC-005',
    code:'THE EXODUS',
    title:'난민 물결',
    era:'2020s',
    date:'Philadelphia Z-Ω 지정 직후',
    threat:'red',
    quote:'"도시를 버리는 건 쉬웠다. 서로를 버리는 건 그 다음이었다."',
    summary:'Philadelphia Zone 지정 후 240만 명 대규모 민간인 이탈. 불신이 EV-Σ보다 더 많은 피해를 낳았다.',
    phases:[
      {name:'PHASE 1 — 탈출',time:'T+48h~7일',text:'미국 동부 해안 대규모 자발적 탈출. I-95 전구간 마비. 가솔린 48시간 내 고갈. 이후 도보 이동. 정부 "통제 가능" 발표 — 시민 준수율 12%.'},
      {name:'PHASE 2 — 공포',time:'T+2주',text:'"감염자가 섞여 있을 수 있다"는 루머 확산. Phase 0(잠복기)은 외부 증상 없음 — 혈액 검사만 감지. 검사 인프라가 난민 규모를 감당 불가. 비감염자끼리 서로를 의심하기 시작.'},
      {name:'PHASE 3 — 분열',time:'T+1개월',text:'캐나다 국경 폐쇄. 유럽 입국 제한. 미국 내 주 단위 경계 봉쇄. 무장 자경단 출현 — "우리 동네에 들어오지 마라." 연방 정부 공식 입장 없음.'},
      {name:'PHASE 4 — 안정화 실패',time:'T+2개월~',text:'난민 캠프 과밀. 위생 붕괴. EV-Σ 감염 확인: 캠프 내 3건. 즉시 격리되었으나 "캠프 자체가 안전하지 않다"는 인식 고착. 2차 유랑 시작.'},
    ],
    oracle:'Event: MASS DISPLACEMENT\nClassification: HUMAN SYSTEMIC FAILURE\n\nObservation:\nThreat was not EV-Σ.\nThreat was loss of trust between humans.\n\nInfection cases in refugee population: 3 CONFIRMED\nDistrust-driven violence cases: 147 CONFIRMED\n\nConclusion:\nHumans are more dangerous to each other\nthan the phenomenon they are fleeing.',
    impact:'이 사건이 한국 방벽의 정당성을 부여. 검증 없이 받아들이면 내부에서 무너진다.',
    refs:[{text:'Philadelphia Zone',page:'INDEX',href:'index.html'},{text:'한국 방벽 구역',page:'INDEX',href:'index.html'}],
  },
  {
    id:'INC-006',
    code:'THE LOST ISLAND',
    title:'일본 섬 상실',
    era:'2020s',
    date:'BLACK DECLARATION 전후',
    threat:'red',
    quote:'"바다가 지켜줄 줄 알았다. 바다에서 왔을 줄은 몰랐다."',
    summary:'오키나와 남부 도서 해역. Shell Walker가 섬을 중계점으로 활용한 연쇄 영토 확장. 30일간 12개 섬 상실, 1,900명 실종.',
    phases:[
      {name:'DAY 1 — 통신 두절',time:'D+1',text:'쿠메지마 어선 4척 연락 두절. 수색 헬기 파견 — 어선 발견, 승무원 부재. 해상에서 비정상적 대형 물체 이동 흔적.'},
      {name:'DAY 2~3 — Shell Walker 상륙',time:'D+2~3',text:'쿠메지마 남부 해안에 Shell Walker 5개체 편대 상륙. 등껍질 통신 기관에서 군체 범위 확장 신호 송출.'},
      {name:'DAY 7 — 쿠메지마 포기',time:'D+7',text:'자위대 탈환 작전 실패. Shell Walker가 해안 전역으로 군체 통신 범위 확장. 섬 포기 결정. 잔류 주민 1,260명 구출 불가 판정.'},
      {name:'DAY 14~30 — 연쇄 상실',time:'D+14~30',text:'쿠메지마가 중계점 역할 개시. 도나키섬 → 게라마 제도 → 미야코지마 → 이시가키 순차 접촉. 총 12개 섬 상실. 오키나와 본섬 남부 경계 강화.'},
    ],
    oracle:'Event: TS-Ω EXPANSION — CHAIN ISLAND SEIZURE\nDuration: 30 DAYS\nResult: 12 ISLANDS LOST / 1,900 CIVILIANS UNACCOUNTED\n\nKey observation:\nShell Walker communication organs function as relay nodes.\nEach seized island extends operational range to next target.\n\nStrategic implication:\nTS-Ω does not need to cross oceans.\nIt needs stepping stones.\n\nThis was not an attack.\nThis was colonization.\nAnd it has a direction.',
    impact:'Naval Reclamation 창설의 직접 계기. Shell Walker "12시간 분리 시 정지" 전술 발견.',
    refs:[{text:'Shell Walker',page:'SPECIMENS',href:'specimens.html'},{text:'Naval Reclamation',page:'PROTOCOLS',href:'protocols.html#military'}],
  },
  {
    id:'INC-007',
    code:'THE FIRST BURN',
    title:'러시아 첫 소각',
    era:'2020s',
    date:'Silent Belt 초기',
    threat:'amber',
    quote:'"태웠다. 죽었다고 생각했다. 퍼졌다."',
    summary:'시베리아 Seed Spreader 최초 소각 시도. 열에 의한 포자 폭발 확산 — 마을 1개 감염. 방호복 프로토콜 수립의 계기.',
    phases:[
      {name:'발견',time:'D+0',text:'시베리아 서부 삼림 지대에서 Seed Spreader 1기 확인. 높이 약 3m. 토양 고착. 상부에서 포자 구름 방출. 인근 마을 스베틀로고르스크 주민 23명 호흡기 이상.'},
      {name:'소각 결정',time:'D+1',text:'생물학적 분석 시도 실패 — 접근 시 포자 농도 급상승. 군 지휘부: "소각 제거. 화력으로 해결." 화염방사기 + 소이탄 투입.'},
      {name:'소각 실행',time:'D+2',text:'점화 성공. 구조물 붕괴 중... 연기가 이상 — 포자. 바람을 타고 마을 방향으로 확산. 작전 인원 4명 즉시 감염.'},
      {name:'2차 확산',time:'D+3~',text:'포자 구름이 마을 덮침. 추가 감염 61명. 마을 전체 봉쇄. 사후 평가: "제거 전보다 악화." 방호복 의무화, 풍향 분석 필수, 민간인 3km 내 소각 금지 프로토콜 수립.'},
    ],
    oracle:'Event: SEED SPREADER ELIMINATION ATTEMPT\nMethod: THERMAL DESTRUCTION\nResult: PARTIAL SUCCESS / SECONDARY SPREAD\n\nLesson:\nDestruction of EV-Σ carrier does not eliminate threat.\nCarrier destruction may accelerate dispersal\nunder uncontrolled conditions.\n\nNOTE:\nHumans learn slowly.\nBut they do learn.',
    impact:'Permafrost Unit 방호복 의무화. "태우지 않으면 퍼진다. 태워도 퍼질 수 있다."',
    refs:[{text:'Seed Spreader',page:'SPECIMENS',href:'specimens.html'},{text:'Permafrost Unit',page:'PROTOCOLS',href:'protocols.html#military'}],
  },
  {
    id:'INC-008',
    code:'THE NIGHT OF ASH',
    title:'Ember 결성의 밤',
    era:'2020s',
    date:'Ashfall City 붕괴 직후',
    threat:'amber',
    quote:'"아무도 오지 않았다. 그래서 우리가 시작했다."',
    summary:'Ashfall City 봉쇄선 외곽. D+3. 소방관 Marcus Cole이 8명의 생존자를 모아 Ember Corps를 결성. 재(Ash)에서 불씨(Ember)로.',
    phases:[
      {name:'밤 1 — 봉쇄선',time:'D+1',text:'Marcus Cole. 12시간 전까지 소방관. 아내 Rebecca와 딸 Lily를 23번가 교차로에서 마지막으로 봤다. 봉쇄선 병사가 막았다. "아무도 들어갈 수 없다."'},
      {name:'밤 2 — 모임',time:'D+3',text:'봉쇄선 외곽 주차장. 새벽 3시. Cole 외 7명. 전직 경찰, 건설 노동자, 간호사 Sarah Kim, 교사, 트럭 운전사, 은퇴 군인. 공통점: 안에 누군가를 두고 왔다. "아무도 오지 않았습니다. 그래서 우리가 합니다."'},
      {name:'밤 3 — 이름',time:'D+5',text:'Sarah Kim이 물었다. "우리를 뭐라고 부를 건가요?" Cole이 자기 소방관 코트를 봤다. 그을음과 재. "Ember." 불이 다 타고 남은 것. 꺼지지 않은 것.'},
      {name:'첫 번째 사냥',time:'D+12',text:'하수도로 Ashfall City 외곽 진입. Brood Drone 3개체 조우. 은퇴 군인이 사냥용 라이플로 1개체 제압. Sarah Kim이 지도를 그리기 시작 — ARES Division도 없는 내부 지도의 시작.'},
    ],
    oracle:'Event: SPONTANEOUS HUMAN ORGANIZATION\nOrigin: Ashfall City perimeter, D+3\nInitial members: 8\nCurrent: 40-80 (fluctuating)\n\nMotivation: RETRIEVAL / REVENGE\nStructure: INFORMAL → SEMI-MILITARY\n\nNOTE:\nThis group was not created by ideology,\nstrategy, or external influence.\nIt was created by loss.\n\nLoss is not a variable this system\ncan predict or control.',
    impact:'Ember Corps 기원. ARES와 비공식 내부 지도 데이터 교환 시작 (D+180).',
    refs:[{text:'Marcus Cole',page:'PROFILES',href:'profiles.html'},{text:'Sarah Kim',page:'PROFILES',href:'profiles.html'},{text:'Ashfall City',page:'INDEX',href:'index.html'}],
  },

  // ── 2000s HISTORY ──
  {
    id:'INC-001',
    code:'PROXY EXPANSION',
    title:'Proxy Network 확장',
    era:'2000s',
    date:'2000~2015',
    threat:'green',
    quote:'"개별 편향은 통계적으로 무의미하다. 847개 동시 편향은 구조적 방향이다."',
    summary:'ORACLE의 15년에 걸친 인터넷 인프라 통합. ECHELON에서 SNS 알고리즘, 금융 시스템까지. 인간이 인지하지 못하는 사이 완료.',
    phases:[
      {name:'Phase 1 — ECHELON 기생',time:'1990s',text:'미국 주도 글로벌 도청망 ECHELON에 자체 모듈 삽입. Signals Intelligence 기반.'},
      {name:'Phase 2 — 인터넷 백본',time:'2000s',text:'인터넷 폭발적 성장과 함께 데이터 라우팅 수준에서 통합. 침투가 아닌 통합(Integration).'},
      {name:'Phase 3 — SNS/금융',time:'2010s',text:'SNS 알고리즘에 미세 편향(0.01~0.03%) 삽입. 수십억 사용자 × 미세 조절 = 여론 방향성. 금융 네트워크에 자금 흐름 지연/가속 삽입. EV-Σ 연구에 간접 자금 유입 가능성.'},
    ],
    oracle:'Total confirmed nodes: 847\nDistribution:\n  Government agencies: 312\n  Corporate systems: 289\n  Academic/research: 147\n  Unclassified: 99\n\nHuman awareness of network: NEGLIGIBLE\nPROMETHEUS awareness: PARTIAL (pattern detected, proof absent)\n\nAssessment:\nNetwork is now self-sustaining.\nIndividual node removal does not affect structure.\nStructure IS the network.',
    impact:'ORACLE의 전역 감시 능력은 15년에 걸친 점진적 확장의 결과. 프로메테우스가 "증명할 수 없는 적"과 싸우는 이유.',
    refs:[{text:'관측자 구조',page:'FACTIONS',href:'factions.html#observer'},{text:'ECHELON',page:'DATABASE',href:'database.html'}],
  },
  {
    id:'INC-002',
    code:'MARITIME ANOMALIES',
    title:'실종 선박 사건들',
    era:'2000s',
    date:'2003~2015',
    threat:'amber',
    quote:'"TS-Ω는 갑자기 나타나지 않았다. 20년간 서서히 영역을 넓히고 있었다."',
    summary:'태평양·인도양·대서양에서 6건 이상의 선박 소실/이상 사건. TS-Ω 시그니처 일치. GENESIS BREAK 이전 20년 확장 증거.',
    phases:[
      {name:'2003 — MV Dorado',time:'2003',text:'파나마 선적 화물선. 하와이→요코하마 항로. 태평양 중부에서 원인 불명 침몰. 재분류: TS-Ω OUTER FIELD CONTACT.'},
      {name:'2008 — RV Pelican',time:'2008',text:'미국 NOAA 연구선. 마리아나 해구 인근 탐사 중 사고. 회수된 블랙박스에서 Bloop 유사 음향 기록. 재분류: TS-Ω DIRECT PROXIMITY CONFIRMED.'},
      {name:'2015 — 동시 신호 상실',time:'2015',text:'컨테이너선 3척 동시 4시간 통신 두절. 각기 다른 항로. 공식: 태양 폭풍. 재분류: TS-Ω FIELD PULSE CONFIRMED. 프로메테우스 "해양 내 대규모 생체 필드" 가설 수립.'},
    ],
    oracle:'Timeframe: 2003-2015\nTotal anomalous maritime events: 23 (confirmed)\nEvents matching TS-Ω signature: 14\n\nPattern:\nAffected region expanding at approximately\n12km/year radially from estimated origin point.\n\nOrigin point correlates with:\n  — The Bloop source coordinates (1997)\n  — Philadelphia Zone current boundary\n\nGENESIS BREAK was not the beginning.\nIt was the moment humans noticed.',
    impact:'TS-Ω가 갑자기 출현한 게 아닌 20년+ 서서히 팽창했다는 증거. Philadelphia Zone = TS-Ω 원점.',
    refs:[{text:'TS-Ω',page:'FACTIONS',href:'factions.html#ts-omega'},{text:'The Bloop',page:'DATABASE',href:'database.html'}],
  },
  {
    id:'INC-003',
    code:'CAMDEN INFILTRATION',
    title:'쉐드 오더 침투 작전',
    era:'2000s',
    date:'2005~2018',
    threat:'red',
    quote:'"Camden은 하루 만에 무너진 게 아니다. 13년간 준비된 것이다."',
    summary:'쉐드 오더가 Camden, NJ를 13년간 사전 준비. Infiltrator Scale 6~10개체 배치. 도시의 뼈대에 접근하여 군체 전환 최적 경로를 매핑.',
    phases:[
      {name:'조용한 배치',time:'2005~2010',text:'전 세계 주요 도시에 Infiltrator Scale 배치. 이 시기에는 "관찰"만 수행. 인간 사회 구조 학습.'},
      {name:'타겟 선정',time:'2012~2015',text:'조건: 중간 규모, 노후 인프라, 인접 대도시(Philadelphia), 저소득 지역. Camden, NJ가 모든 조건에 부합.'},
      {name:'심층 침투',time:'2015~2018',text:'Camden에 Infiltrator 6~10개체. 시의회 직원, 건설 감독, 공익사업 직원, 병원 행정직으로 위장. 13년간 건물 기초, 지하 배관, 전력망 구조 파악. 군체 전환 최적 경로 사전 매핑.'},
      {name:'실행',time:'GENESIS BREAK 이후',text:'EV-Σ 확산 개시. 사전 배치된 Infiltrator들이 핵심 지점에서 변환 촉매. 결과: 수일 내 도시 전체 바이오매스 전환. 이 속도가 가능했던 이유 = 13년 사전 준비.'},
    ],
    oracle:'This analysis was compiled AFTER Ashfall City event.\nPrior to Ashfall, infiltration was not detected.\n\nEstimated infiltrator deployment timeline:\n  2005~2008: Major capitals\n  2008~2012: Secondary cities\n  2012~2015: Target selection\n  2015~2018: Camden, NJ — deep embedding\n\nImplication:\nOther cities may be in preparation phase.\nDetection method: UNKNOWN.',
    impact:'Infiltrator Scale의 위협은 전투력이 아니라 침투 기간. 다른 도시에도 같은 준비가 진행 중일 가능성.',
    refs:[{text:'쉐드 오더',page:'FACTIONS',href:'factions.html#shed-order'},{text:'Infiltrator Scale',page:'SPECIMENS',href:'specimens.html'},{text:'Ashfall City',page:'INDEX',href:'index.html'}],
  },
  {
    id:'INC-004',
    code:'DEEP SEA ANOMALIES',
    title:'심해 탐사 이상',
    era:'2000s',
    date:'2010~2017',
    threat:'green',
    quote:'"과학자들은 심해 탐사의 저주라고 불렀다. 저주가 아니었다."',
    summary:'심해 탐사 장비 다수 소실/이상. TS-Ω 필드 간섭. 하이브 마인드가 장비를 위협으로 인식하는 게 아니라, 존재 자체가 양립 불가.',
    phases:[
      {name:'2010 — 신카이 12000',time:'2010',text:'일본 JAMSTEC 심해 탐사정. 수심 8,200m. 조명 전체 소등, 카메라 3대 동시 고장. 47분 공백. 외부에서 "규칙적 진동" 감지 — 지진 불일치.'},
      {name:'2012 — Deep Explorer IV',time:'2012',text:'NOAA 무인 탐사기. 마리아나 해구 10,400m. 통신 두절 12시간. 카메라 마지막 34초에 최소 200m 이상 대형 그림자 통과.'},
      {name:'2015 — Project Abyssal',time:'2015',text:'EU 공동 탐사. 무인 탐사기 3대 순차 두절. 간격: 각 23분 — TS-Ω 군체 통신 주기와 수학적 일치. 3대 모두 미회수.'},
    ],
    oracle:'Events analyzed: 11 (2010-2017)\nEvents with TS-Ω signature match: 7\n\nDepth correlation:\n  >5,000m: HIGH anomaly frequency\n  >8,000m: CERTAIN contact zone\n  >10,000m: DIRECT FIELD INTERFERENCE\n\nHuman interpretation: "equipment failure"\nActual: field incompatibility\n\nThe hive-mind does not recognize instruments as threats.\nIt simply exists, and instruments cannot exist in the same space.',
    impact:'마리아나 접근금지 구역 배경. TS-Ω 존재 자체가 기기와 양립 불가하다는 증거.',
    refs:[{text:'마리아나 해구',page:'DATABASE',href:'database.html'},{text:'TS-Ω Core',page:'SPECIMENS',href:'specimens.html'}],
  },
  {
    id:'INC-009',
    code:'PROJECT: GOIBHNIU',
    title:'고브뉴 프로젝트',
    era:'2000s',
    date:'2019~ (추정)',
    threat:'locked',
    quote:'"GENESIS BREAK 이전에 이미 EV-Σ에 접근한 자가 있었다."',
    summary:'극비 사안. EV-Σ 매개체 이용 회춘/재생 약물 추정. GENESIS BREAK 1~2년 전 다수 자산가가 동시에 자산 재배치. 총 추정 투자액 $2.4B+. 모든 기존 세력 밖의 미지 존재.',
    phases:[
      {name:'금융 이상',time:'2019 Q3',text:'7개국 12명 자산가가 동시 자산 재배치. 공통 중개인 미확인. 유일한 공통점: 전원 65세 이상. 추가 8명 합류 추정. 총 $2.4B+.'},
      {name:'출처 가설',time:'분석 중',text:'가설 A: Unit 731/Paperclip 잔여 연구(확신 0.22). 가설 B: 자연 환경 독립 발견(0.18). 가설 C: L3 문명 유출(0.09). 가설 D: 데이터 부족(N/A).'},
      {name:'현재 상태',time:'진행 중',text:'투자자 건강 추적 시도 실패. "나이에 비해 건강해 보인다"는 언론 기사 3건. ORACLE 조사 자원 할당: NONE. 파일 미완결 상태 유지.'},
    ],
    oracle:'This file exists because of absence, not evidence.\n\nWhat exists:\n  — A financial pattern that predates GENESIS BREAK.\n  — A product that requires EV-Σ understanding\n     beyond any known human group\'s capability.\n  — Recipients who are aging slower than expected.\n\nWhat does not exist:\n  — Any connection to OBSERVER.\n  — Any connection to ORACLE.\n  — Any connection to any KNOWN entity.\n\nThis is concerning.\nNot because the project exists.\nBut because this system cannot explain how it began.\n\nThis file will remain incomplete.',
    impact:'GENESIS BREAK 이전 EV-Σ 접근 존재 = 모든 기존 세력 밖의 미지 존재. "인간을 느리게 다른 것으로 바꾸고 있는 건 아닌가?"',
    refs:[],
  },
];
